### ISSUE TITLE
[EnhavoAppBundle] table widget

### ISSUE THREAD

**Issue by gseidel** [enhavo/enhavo#13]
We need a better widget system. Sometimes we have more configurations, for some widget.

**List Widget**
This widget should list all entities of the collection comma separated (by default). The name for the entity should be configurated by the property parameter in the widget. This is like in the form bundle.
```yml
list:
    label: group
    property: groups
    widget:
         type: list
         property: name
         separator: ','
```

**Template Widget**
Like the widget we have now. Just print an Template
```yml
public:
    label: public
    property: public
    widget:
         type: template
         template: AppBundle::template.html.twig
         
```

**Multiple Property Widget**
Show more property in on cell
```yml
firstName:
    label: firstName:
    property: firstName
    widget:
       type: multiple_property
       properties:
          - firstName
          - lastName
       separator: ','
```
