### ISSUE TITLE
[EnhavoAppBundle] assets manageable by routing

### ISSUE THREAD

**Issue by gseidel** [enhavo/enhavo#14]
Stylesheet and javascript should be manageable by routing.

Example:

``` yml
stylesheets:
    esperanto_app_style:
        resource: '@esperantoAppBundle/Resource/public/css/style.css'
        depends: ~
javascripts:
    esperanto_app_bootstrap:
        resource: '@esperantoAppBundle/Resource/public/js/bootstrap.css'
        depends: jquery
```
