### ISSUE TITLE
[EnhavoGridBundle] also using form service in item configuration

### ISSUE THREAD

**Issue by gseidel** [enhavo/enhavo#6]
At the moment we can configure our items in the config like this:

``` yaml
esperanto_content:
    items:
        youtube:
            model: esperanto\ProjectBundle\Entity\Youtube
            form: esperanto\ProjectBundle\Form\Type\YoutubeType
            repository: esperantoProjectBundle:Youtube
            template: esperantoProjectBundle:ItemType:youtube.html.twig
            label: Youtube
```

You can see that for the form class we use a concrete class name, but we should give the user also the possibility to use the form as a service.

So this should also be possible:

``` yaml
esperanto_content:
    items:
        youtube:
            model: esperanto\ProjectBundle\Entity\Youtube
            form: esperanto_content_item_youtube
            repository: esperantoProjectBundle:Youtube
            template: esperantoProjectBundle:ItemType:youtube.html.twig
            label: Youtube
```
