### ISSUE TITLE
[DashboardBundle] Grid config

### ISSUE THREAD

**Issue by gseidel** [enhavo/enhavo#927]
We have to refactor the DashboardBundle. Like in other bundles we want to config our dashboard in a config yaml with the  type pattern.

The config could look like this:

```
enhavo_dashboard:
    dashboard:
        article_number:
            type: number
            label: Total Articles
            provider:
                type: article
                key: article_total
        google_analytics:
            type: google_analytics
```
